{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name')|replace("tethysapp-", "")|lower %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

about:
  author: {{ data.get('author')}}
  description: {{ data.get('description')}}
  license: "{'name': 'tethysapp-geoserver_app', 'version': '0.0.1', 'description': '', 'long_description': '', 'keywords': '', 'author': '', 'author_email': '', 'url': '', 'license': '', 'app_type': 'tethysapp', 'tethys_version': '<=3.4.4', 'dev_url': 'https://github.com/tethysplatform/tethysapp-geoserver_app'}"
  dev_url: {{ data.get('dev_url') }}

outputs:
  - name: {{ name }}
extra:
  author_email: ''
  keywords: []
  recipe-maintainers:
  - TethysAppWarehouse

build:
  noarch: python
  preserve_egg_dir: true
  script: python setup.py install --record=record.txt
requirements:
  build:
  - python
  run: null
source:
  path: ..
